#!/usr/bin/env bash
# Auto-generated by audit_images.sh v2.0 on 2026-02-17
# Updated with direct upload.wikimedia.org thumbnail URLs + case fixes.
#
# Downloads all missing images identified by the audit.
# Continues on failure (does not abort on first error).
#
# Usage:  bash scripts/download-missing.sh

set -u  # no pipefail — continue on per-image failures
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UA="YawpMS-ImageBot/1.0 (educational textbook project)"
OK=0
FAIL=0

download() {
  local dest="$1" url="$2" fallback="${3:-}"
  local dir; dir=$(dirname "$dest")
  mkdir -p "$ROOT/$dir"
  echo -n "  Downloading $dest ... "
  for attempt in 1 2 3; do
    if curl -sL --fail --max-time 60 -A "$UA" "$url" -o "$ROOT/$dest" 2>/dev/null; then
      local size; size=$(stat -c%s "$ROOT/$dest" 2>/dev/null || stat -f%z "$ROOT/$dest" 2>/dev/null || echo 0)
      if [ "$size" -gt 1000 ]; then
        echo "OK ($(( size / 1024 ))KB)"
        OK=$((OK + 1))
        return 0
      fi
    fi
    sleep $((attempt * 2))
  done
  # Try fallback URL if provided
  if [ -n "$fallback" ]; then
    echo -n "trying fallback ... "
    for attempt in 1 2 3; do
      if curl -sL --fail --max-time 60 -A "$UA" "$fallback" -o "$ROOT/$dest" 2>/dev/null; then
        local size; size=$(stat -c%s "$ROOT/$dest" 2>/dev/null || stat -f%z "$ROOT/$dest" 2>/dev/null || echo 0)
        if [ "$size" -gt 1000 ]; then
          echo "OK via fallback ($(( size / 1024 ))KB)"
          OK=$((OK + 1))
          return 0
        fi
      fi
      sleep $((attempt * 2))
    done
  fi
  echo "FAILED"
  rm -f "$ROOT/$dest"
  FAIL=$((FAIL + 1))
  return 0  # don't abort script
}

UPLOAD="https://upload.wikimedia.org/wikipedia/commons"
W="https://commons.wikimedia.org/wiki/Special:FilePath"

echo "Downloading 9 missing images..."
echo ""

# ── Maps (6) ──

# Ch5: American Revolution battles map
download "images/ch5/revolution-battles-map.png" \
  "$UPLOAD/thumb/7/7e/American_Revolutionary_War_battles_map.svg/600px-American_Revolutionary_War_battles_map.svg.png" \
  "$W/American_Revolutionary_War_battles_map.svg?width=600"

# Ch9: Indian land cessions
download "images/ch9/indian-cessions-map.jpg" \
  "$UPLOAD/thumb/8/82/Indiancessions.jpg/800px-Indiancessions.jpg" \
  "$UPLOAD/8/82/Indiancessions.jpg"

# Ch11: Domestic slave trade routes
download "images/ch11/domestic-slave-trade-map.png" \
  "$UPLOAD/thumb/1/19/Slave_trade_routes_in_the_USA.svg/800px-Slave_trade_routes_in_the_USA.svg.png" \
  "$W/Slave_trade_routes_in_the_USA.svg?width=800"

# Ch12: Oregon Territory 1848 (NB: uppercase T in Territory)
download "images/ch12/oregon-territory-map.png" \
  "$UPLOAD/thumb/3/39/Oregon_Territory_1848.svg/600px-Oregon_Territory_1848.svg.png" \
  "$W/Oregon_Territory_1848.svg?width=600"

# Ch13: Compromise of 1850
download "images/ch13/compromise-1850-map.png" \
  "$UPLOAD/thumb/0/02/Compromise_of_1850.png/800px-Compromise_of_1850.png" \
  "$W/Compromise_of_1850.png?width=800"

# Ch15: Reconstruction military districts (NB: lowercase m,d)
download "images/ch15/reconstruction-districts-map.png" \
  "$UPLOAD/thumb/c/c3/Reconstruction_military_districts.svg/600px-Reconstruction_military_districts.svg.png" \
  "$W/Reconstruction_military_districts.svg?width=600"

# ── Photos (2) ──

# Ch8: Lowell mills
download "images/ch8/lowell-mills.jpg" \
  "$UPLOAD/thumb/0/00/Lowell_Massachusetts_Merrimack_Mills.jpg/640px-Lowell_Massachusetts_Merrimack_Mills.jpg" \
  "$W/Lowell_Massachusetts_Merrimack_Mills.jpg?width=640"

# Ch8: South Street NYC (Bennett painting)
download "images/ch8/south-street-nyc.jpg" \
  "$UPLOAD/thumb/7/77/William_James_Bennett_-_View_of_South_Street%2C_from_Maiden_Lane%2C_New_York_City_-_Google_Art_Project.jpg/640px-William_James_Bennett_-_View_of_South_Street%2C_from_Maiden_Lane%2C_New_York_City_-_Google_Art_Project.jpg" \
  "$W/William_James_Bennett_-_View_of_South_Street%2C_from_Maiden_Lane%2C_New_York_City_-_Google_Art_Project.jpg?width=640"

# ── Primary Sources (1) ──

# Ch6: The Providential Detection
download "primary-sources/images/ch6-providential-detection.jpg" \
  "$UPLOAD/thumb/f/f8/The_Providential_Detection.jpg/800px-The_Providential_Detection.jpg" \
  "$UPLOAD/f/f8/The_Providential_Detection.jpg"

echo ""
echo "============================================"
echo "  Results:  OK=$OK  FAILED=$FAIL  Total=9"
echo "============================================"
if [ "$FAIL" -gt 0 ]; then
  echo "  Some images failed. Check URLs manually or try:"
  echo "    bash scripts/download_all_maps.sh"
  echo "    bash scripts/download_all_images.sh"
fi
