#!/usr/bin/env bash
# Auto-generated by audit_images.sh v2.0 on 2026-02-17
# Downloads all missing images identified by the audit.
#
# Usage:  bash scripts/download-missing.sh

set -eo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UA="YawpMS-ImageBot/1.0 (educational textbook project)"

download() {
  local dest="$1" url="$2"
  local dir; dir=$(dirname "$dest")
  mkdir -p "$ROOT/$dir"
  echo -n "  Downloading $dest ... "
  for attempt in 1 2 3; do
    if curl -sL --fail --max-time 60 -A "$UA" "$url" -o "$ROOT/$dest" 2>/dev/null; then
      local size; size=$(stat -c%s "$ROOT/$dest" 2>/dev/null || echo 0)
      if [ "$size" -gt 1000 ]; then
        echo "OK ($(( size / 1024 ))KB)"
        return 0
      fi
    fi
    sleep $((attempt * 2))
  done
  echo "FAILED"
  return 1
}

echo "Downloading missing images..."
echo ""
download "images/ch11/domestic-slave-trade-map.png" "https://commons.wikimedia.org/wiki/Special:FilePath/Slave_trade_routes_in_the_USA.svg?width=800"
download "images/ch12/oregon-territory-map.png" "https://commons.wikimedia.org/wiki/Special:FilePath/Oregon_territory_1848.svg?width=600"
download "images/ch13/compromise-1850-map.png" "https://commons.wikimedia.org/wiki/Special:FilePath/Compromise_of_1850.png?width=800"
download "images/ch15/reconstruction-districts-map.png" "https://commons.wikimedia.org/wiki/Special:FilePath/Reconstruction_Military_Districts.svg?width=600"
download "images/ch5/revolution-battles-map.png" "https://commons.wikimedia.org/wiki/Special:FilePath/American_Revolutionary_War_battles_map.svg?width=600"
download "images/ch8/lowell-mills.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Lowell_Massachusetts_Merrimack_Mills.jpg?width=640"
download "images/ch8/south-street-nyc.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/William_James_Bennett_-_View_of_South_Street%2C_from_Maiden_Lane%2C_New_York_City_-_Google_Art_Project.jpg?width=640"
download "images/ch9/indian-cessions-map.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Indiancessions.jpg?width=800"
download "primary-sources/images/ch6-providential-detection.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/The_Providential_Detection.jpg?width=800"

echo ""
echo "Done. 9 images attempted."
